#!/usr/bin/env bash
../createslideshow \
--infrastructure=../infrastructure \
--directory=a93-27dez2003 \
--maintitle="Thomas Dreibholz's Abschluß '93 Bildergalerie" \
--maindescription=a93-27dez2003-maintitle.html \
--stylesheet=stylesheet.css \
--background=background.png \
--shortcuticon=icon-abschluss93.png \
--slideshow \
--head=a93-head.html \
--tail=a93-tail.html \
--fullsizewidth=1280 \
--fullsizeheight=960 \
--enumerate \
--noindex \
--block="Bilder vom Treffen am 27.12.2003" \
--blockdescription=a93-27dez2003-maintitle.html \
"/home/dreibh/Bilder/stufentreffen_12_03/"*.JPG \
$@ \
--
