#!/usr/bin/env bash
shopt -s extglob

./slideshow2 \
--directory=bakeoff5 \
--maintitle="The 5th SCTP Interop" --maindescription=bakeoff5-maintitle.html \
--stylesheet=stylesheet.css \
--background=background.png \
--shortcuticon=icon-default.png \
--slideshow \
--head=head.html \
--tail=tail.html \
--fullwidth=1280 \
--fullheight=960 \
--enumerate \
\
--block="Part 1" \
"/tmp/photo-archive/sctp-bakeoff-essen-2002/bakeoff1/"*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 2" \
"/tmp/photo-archive/sctp-bakeoff-essen-2002/bakeoff2/"*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 3" \
"/tmp/photo-archive/sctp-bakeoff-essen-2002/bakeoff3/"*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 4" \
"/tmp/photo-archive/sctp-bakeoff-essen-2002/bakeoff4/"*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 5" \
"/tmp/photo-archive/sctp-bakeoff-essen-2002/bakeoff5/"*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 6" \
"/tmp/photo-archive/sctp-bakeoff-essen-2002/bakeoff5/"*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 7" \
"/tmp/photo-archive/sctp-bakeoff-essen-2002/bakeoff7/"*.@(jpg|JPG|jpeg|JPEG) \
$@ \
--
