#!/usr/bin/env bash
CNV=convert

# -draw 'gravity SouthEast text 20,20,"Copyright (C) 2004 by Thomas Dreibholz, http://www.exp-math.uni-essen.de/~dreibh/"'
$CNV Abingdon.jpeg -interlace line -font ps:times -fill blue -resize 1200x960 AbingdonDisplay.jpeg
$CNV Leverkusen.jpeg -interlace line -font ps:times -fill blue -resize 1200x960 LeverkusenDisplay.jpeg
$CNV Lichtbild.jpeg -interlace line -font ps:times -fill blue -resize 1200x960 LichtbildDisplay.jpeg
$CNV Miami.jpeg -interlace line -font ps:times -fill blue -resize 1200x960 MiamiDisplay.jpeg
$CNV Newark.jpeg -interlace line -font ps:times -fill blue -resize 960x1200 NewarkDisplay.jpeg
$CNV Papeete.jpeg -interlace line -font ps:times -fill blue -resize 1200x960 PapeeteDisplay.jpeg
$CNV PapeeteII.jpeg -interlace line -font ps:times -fill blue -resize 1200x960 PapeeteIIDisplay.jpeg
$CNV Perth.jpeg -interlace line -font ps:times -fill blue -resize 1200x960 PerthDisplay.jpeg
$CNV SanFrancisco.jpeg -interlace line -font ps:times -fill blue -resize 1200x960 SanFranciscoDisplay.jpeg
$CNV Sydney.jpeg -interlace line -font ps:times -fill blue -resize 1200x960 SydneyDisplay.jpeg
$CNV Tampa.jpeg -interlace line -font ps:times -fill blue -resize 1200x960 TampaDisplay.jpeg
$CNV Torbole.jpeg -interlace line -font ps:times -fill blue -resize 1200x960 TorboleDisplay.jpeg
