#!/bin/bash
shopt -s extglob

./slideshow2 \
--directory=msn2004 \
--maintitle="Thomas Dreibholz's Travel to the MSN2004" --maindescription=msn2004-maintitle.html \
--stylesheet=stylesheet.css \
--background=background.png \
--shortcuticon=icon-default.png \
--slideshow \
--head=head.html \
--tail=tail.html \
--fullsizewidth=1280 \
--fullsizeheight=960 \
--enumerate \
\
--block="Part 1 - July 07, 2004" \
"/tmp/photo-archive/msn2004/2004_07_07"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 2 - July 08, 2004" \
"/tmp/photo-archive/msn2004/2004_07_08"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 3 - July 09, 2004" \
"/tmp/photo-archive/msn2004/2004_07_09"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 4 - July 10, 2004" \
"/tmp/photo-archive/msn2004/2004_07_10"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 5 - July 11, 2004" \
"/tmp/photo-archive/msn2004/2004_07_11"/*.@(jpg|JPG|jpeg|JPEG) \
$@ \
--
