#!/usr/bin/env bash
shopt -s extglob

./slideshow2 \
--directory=msn2003 \
--maintitle="Thomas Dreibholz's Travel to the MSN2003" --maindescription=msn2003-maintitle.html \
--stylesheet=stylesheet.css \
--background=background.png \
--shortcuticon=icon-default.png \
--slideshow \
--head=head.html \
--tail=tail.html \
--fullsizewidth=1280 \
--fullsizeheight=960 \
--enumerate \
\
--block="Part 1 - July 02, 2003" \
"/tmp/photo-archive/msn2003/2003_07_02"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 2 - July 03, 2003" \
"/tmp/photo-archive/msn2003/2003_07_03"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 3 - July 04, 2003" \
"/tmp/photo-archive/msn2003/2003_07_04"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 4 - July 05, 2003" \
"/tmp/photo-archive/msn2003/2003_07_05"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 5 - July 06, 2003" \
"/tmp/photo-archive/msn2003/2003_07_06"/*.@(jpg|JPG|jpeg|JPEG) \
$@ \
--
