#!/bin/bash
./slideshow2 \
--directory=a93-27dez2003 \
--maintitle="Thomas Dreibholz's Abschluﬂ '93 Bildergalerie" --maindescription=a93-27dez2003-maintitle.html \
--stylesheet=stylesheet.css \
--background=background.png \
--shortcuticon=icon-abschluss93.png \
--slideshow \
--head=a93-head.html \
--tail=a93-tail.html \
--fullwidth=1280 \
--fullheight=960 \
--enumerate \
--noindex \
--block="Bilder vom Treffen am 27.12.2003" \
--description=a93-27dez2003-maintitle.html \
"/home/dreibh/stufentreffen_12_03/"*.JPG \
$@ \
--
