#!/bin/bash
shopt -s extglob

./slideshow2 \
--directory=bakeoff7 \
--maintitle="The 7th SCTP Interop" --maindescription=bakeoff7-maintitle.html \
--stylesheet=stylesheet.css \
--background=background.png \
--shortcuticon=icon-default.png \
--slideshow \
--head=head.html \
--tail=tail.html \
--fullsizewidth=1280 \
--fullsizeheight=960 \
--enumerate \
\
--block="Part 1" \
"/tmp/photo-archive/sctp-bakeoff-muenster-2004/2004_07_24"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 2" \
"/tmp/photo-archive/sctp-bakeoff-muenster-2004/2004_07_26"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 3" \
"/tmp/photo-archive/sctp-bakeoff-muenster-2004/2004_07_27"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 4" \
"/tmp/photo-archive/sctp-bakeoff-muenster-2004/2004_07_29"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 5" \
"/tmp/photo-archive/sctp-bakeoff-muenster-2004/2004_07_30"/*.@(jpg|JPG|jpeg|JPEG) \
$@ \
--
