#!/bin/bash
shopt -s extglob

./slideshow2 \
--directory=bakeoff4 \
--maintitle="The 4th SCTP Interop" --maindescription=bakeoff4-maintitle.html \
--stylesheet=stylesheet.css \
--background=background.png \
--shortcuticon=icon-default.png \
--slideshow \
--head=head.html \
--tail=tail.html \
--fullwidth=1024 \
--fullheight=768 \
--enumerate \
--noindex \
--columns=4 \
"/tmp/photo-archive/connectathon2002"/*.@(jpg|JPG|jpeg|JPEG) \
$@ \
--
