#!/bin/bash
shopt -s extglob
./slideshow bakeoff4-index.html $@ \
--maintitle="The 4th SCTP Interop" \
--stylesheet=stylesheet.css \
--enumerate \
--noindex \
--cols=4 \
\
--subdir \
--title="The 4th SCTP Interop" \
--description=bakeoff4-maintitle.html \
"/tmp/photo-archive/connectathon2002/"@(jpg|JPG|jpeg|JPEG) \
--
