#!/bin/bash
shopt -s extglob
./slideshow bakeoff5-index.html $@ \
--maintitle="The 5th SCTP Interop" --maindescription=bakeoff5-maintitle.html \
--stylesheet=stylesheet.css \
--enumerate \
\
--subdir=bakeoff5-block1 \
--title="Part 1" \
"/tmp/photo-archive/sctp-bakeoff-essen-2002/bakeoff1/"*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir=bakeoff5-block2 \
--title="Part 2" \
"/tmp/photo-archive/sctp-bakeoff-essen-2002/bakeoff2/"*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir=bakeoff5-block3 \
--title="Part 3" \
"/tmp/photo-archive/sctp-bakeoff-essen-2002/bakeoff3/"*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir=bakeoff5-block4 \
--title="Part 4" \
"/tmp/photo-archive/sctp-bakeoff-essen-2002/bakeoff4/"*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir=bakeoff5-block5 \
--title="Part 5" \
"/tmp/photo-archive/sctp-bakeoff-essen-2002/bakeoff5/"*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir=bakeoff5-block6 \
--title="Part 6" \
"/tmp/photo-archive/sctp-bakeoff-essen-2002/bakeoff5/"*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir=bakeoff5-block7 \
--title="Part 7" \
"/tmp/photo-archive/sctp-bakeoff-essen-2002/bakeoff7/"*.@(jpg|JPG|jpeg|JPEG) \
--
