#!/bin/bash
shopt -s extglob
./slideshow bakeoff6-index.html $@ \
--maintitle="The 6th SCTP Interop" --maindescription=bakeoff6-maintitle.html \
--stylesheet=stylesheet.css \
--enumerate \
\
--subdir=bakeoff6-block1 \
--title="Part 1" \
"/tmp/photo-archive/sctp-bakeoff-newark-2003/thomas.dreibholz.photos/2003_05_31"/*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir=bakeoff6-block2 \
--title="Part 2" \
"/tmp/photo-archive/sctp-bakeoff-newark-2003/thomas.dreibholz.photos/2003_06_03"/*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir=bakeoff6-block3 \
--title="Part 3" \
"/tmp/photo-archive/sctp-bakeoff-newark-2003/thomas.dreibholz.photos/2003_06_04"/*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir=bakeoff6-block4 \
--title="Part 4" \
"/tmp/photo-archive/sctp-bakeoff-newark-2003/thomas.dreibholz.photos/2003_06_05"/*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir=bakeoff6-block5 \
--title="Part 5" \
"/tmp/photo-archive/sctp-bakeoff-newark-2003/thomas.dreibholz.photos/2003_06_07"/*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir=bakeoff6-block6 \
--title="Part 6" \
"/tmp/photo-archive/sctp-bakeoff-newark-2003/thomas.dreibholz.photos/2003_06_08"/*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir=bakeoff6-block7 \
--title="Part 7" \
"/tmp/photo-archive/sctp-bakeoff-newark-2003/thomas.dreibholz.photos/2003_06_09"/*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir=bakeoff6-block8 \
--title="Part 8" \
"/tmp/photo-archive/sctp-bakeoff-newark-2003/thomas.dreibholz.photos/2003_06_10"/*.@(jpg|JPG|jpeg|JPEG) \
--
