#!/bin/bash

if [ $# -lt 8 ] ; then
   echo "Usage: [Original input] [Full output] [Preview output] [Info output] [Full BB width] [Full BB height] [Preview BB width] [Preview BB height] {--htmlonly}" >&2
   exit 1
fi

if [ $# -ge 9 ] ; then
   if [ $9 == "--htmlonly" ]; then
      if [ ! -e "$4" ]; then
         echo "   Warning: No full-size file $2!"
         exit 1
      fi
      exit 0
   fi
fi

if [ ! -e "$1" ] ; then
   echo "ERROR: Source image "$1" does not exist!" >&2
   exit
fi
if [ -e "$2" ] ; then
   rm -f "$2"
fi
if [ -e "$3" ] ; then
   rm -f "$3"
fi
if [ -e "$4" ] ; then
   rm -f "$4"
fi


ORIGINAL=/tmp/slideshowtmp-original-$RANDOM-$RANDOM-$RANDOM.pnm
FULL=/tmp/slideshowtmp-full-$RANDOM-$RANDOM-$RANDOM.pnm
PREVIEW=/tmp/slideshowtmp-preview-$RANDOM-$RANDOM-$RANDOM.pnm
anytopnm "$1" >$ORIGINAL 2>/dev/null


# echo "Preparing full-size image "$1" (bounding box: $3x$4) -> "$2"..." >&2
if [ $5 -gt 0 -a $6 -gt 0 ] ; then
   pnmscale -xysize "$5" "$6" $ORIGINAL >$FULL
else
   cat $ORIGINAL >$FULL
fi
pnmtojpeg --progressive --optimize --quality=75 $FULL >"$2"


# echo "Preparing preview-size image "$1" (bounding box: $7x$8) -> "$3"..." >&2
pnmscale -xysize "$7" "$8" $ORIGINAL >$PREVIEW
pnmtojpeg --progressive --optimize --quality=75 $PREVIEW >"$3"


# echo "Obtaining sizes..." >&2
getsize $ORIGINAL >"$4"
getsize $FULL >>"$4"
getsize $PREVIEW >>"$4"
#cat $4 >&2


rm -f $ORIGINAL $FULL $PREVIEW
