#!/bin/bash

if [ $# -lt 2 ]; then
   echo "Usage: [Input jpeg] [Output preview jpeg] {--htmlonly}" >&2
   exit 1
fi

if [ ! -e "$1" ]; then
   echo "Error: Input file $1 does not exist!"
   exit 1
fi

if [ $# -ge 3 ]; then
   if [ $3 == "--htmlonly" ]; then
      echo "Test only "$1" -- Okay"
      if [ ! -e "$2" ]; then
         echo "   Warning: No full-size file $2!"
         exit 1
      fi
      exit 0
   fi
fi

if [ -e "$2" ]; then
   rm -f "$2"
fi


# echo "Preparing full-size image "$1"..." >&2
anytopnm "$1" | pnmtojpeg --progressive --optimize --quality=75 >"$2"
