#!/bin/bash
shopt -s extglob

./slideshow2 \
--directory=ict2003 \
--maintitle="Thomas Dreibholz's Travel to the ICT2003" --maindescription=ict2003-maintitle.html \
--stylesheet=stylesheet.css \
--background=background.png \
--shortcuticon=icon-default.png \
--slideshow \
--head=head.html \
--tail=tail.html \
--fullwidth=1024 \
--fullheight=768 \
--enumerate \
\
--block="Day 1 - Travel to Tahiti" \
"/tmp/photo-archive/ict2003/Tahiti, Tag 01"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Day 2 - At the Conference Hotel" \
"/tmp/photo-archive/ict2003/Tahiti, Tag 02"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Day 3 - At the Conference Hotel" \
"/tmp/photo-archive/ict2003/Tahiti, Tag 03"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Day 4 - Environment of the Conference Hotel" \
"/tmp/photo-archive/ict2003/Tahiti, Tag 04"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Day 5 - The Day of my Conference Talk and the Gala Dinner" \
"/tmp/photo-archive/ict2003/Tahiti, Tag 05"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Day 6 - Snorkeling Tour" \
"/tmp/photo-archive/ict2003/Tahiti, Tag 06"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Day 7 - Daytrip to Bora Bora" \
"/tmp/photo-archive/ict2003/Tahiti, Tag 07"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Day 8 - Environment of the Conference Hotel" \
"/tmp/photo-archive/ict2003/Tahiti, Tag 08"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Day 9 - Tamaaraa (Traditional Polynesian Lunch)" \
"/tmp/photo-archive/ict2003/Tahiti, Tag 09"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Day 10 - At the University of French Polynesia" \
"/tmp/photo-archive/ict2003/Tahiti, Tag 10"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Day 11 - Return Travel" \
"/tmp/photo-archive/ict2003/Tahiti, Tag 11"/*.@(jpg|JPG|jpeg|JPEG) \
$@ \
--
