#!/bin/bash
shopt -s extglob

./slideshow2 \
--directory=ietf61 \
--maintitle="The 61st IETF" --maindescription=ietf61-maintitle.html \
--stylesheet=stylesheet.css \
--background=background.png \
--shortcuticon=icon-default.png \
--slideshow \
--head=head.html \
--tail=tail.html \
--fullsizewidth=1280 \
--fullsizeheight=960 \
--enumerate \
\
--block="Part 1" \
"/home/dreibh/ietf-washington-2004/2004_11_06/"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 2" \
"/home/dreibh/ietf-washington-2004/2004_11_07/"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 3" \
"/home/dreibh/ietf-washington-2004/2004_11_08/"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 4" \
"/home/dreibh/ietf-washington-2004/2004_11_09/"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 5" \
"/home/dreibh/ietf-washington-2004/2004_11_10/"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 6" \
"/home/dreibh/ietf-washington-2004/2004_11_11/"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 7" \
"/home/dreibh/ietf-washington-2004/2004_11_12/"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 8" \
"/home/dreibh/ietf-washington-2004/2004_11_13/"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 9" \
"/home/dreibh/ietf-washington-2004/2004_11_14/"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 10" \
"/home/dreibh/ietf-washington-2004/2004_11_15/"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 11" \
"/home/dreibh/ietf-washington-2004/2004_11_16/"/*.@(jpg|JPG|jpeg|JPEG) \
\
$@ \
--
