#!/bin/bash
shopt -s extglob
./slideshow lca2003-index.html $@ \
--maintitle="Thomas Dreibholz's Travel to the LCA2003" --maindescription=lca2003-maintitle.html \
--stylesheet=stylesheet.css \
\
--subdir \
--title="Part 1 - Arrival in Sydney" \
"/tmp/photo-archive/lca2003/A - Bilderserie - Ankunft in Sydney"/*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir \
--title="Part 2 - Botanical Garden of Sydney" \
"/tmp/photo-archive/lca2003/B - Bilderserie - Sydney-Botanischer Garten"/*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir \
--title="Part 3 - AMP Tower and Taronga Zoo" \
"/tmp/photo-archive/lca2003/C - Bilderserie - AMP-Tower und Taronga Zoo"/*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir \
--title="Part 4 - Taronga Zoo" \
"/tmp/photo-archive/lca2003/D - Bilderseite - Taronga Zoo"/*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir \
--title="Part 5 - Aquarium" \
"/tmp/photo-archive/lca2003/E - Bilderserie - Aquarium"/*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir \
--title="Part 6 - Bondi Explorer" \
"/tmp/photo-archive/lca2003/F - Bilderserie - Sydney-Bondi Explorer"/*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir \
--title="Part 7 - Trip to Katoomba" \
"/tmp/photo-archive/lca2003/G - Bilderserie - Sydney-Katoomba"/*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir \
--title="Part 8 - Trip to Katoomba" \
"/tmp/photo-archive/lca2003/H - Bilderserie - Katoomba"/*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir \
--title="Part 9 - Travel to Perth" \
"/tmp/photo-archive/lca2003/I - Bilderserie - Sydney-Perth"/*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir \
--title="Part 10 - Kings Park" \
"/tmp/photo-archive/lca2003/J - Bilderserie - Kings Park"/*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir \
--title="Part 11 - Kings Park and University Tour" \
"/tmp/photo-archive/lca2003/K - Bilderserie - Kings Park and University Tour"/*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir \
--title="Part 12 - At the University of Western Australia" \
"/tmp/photo-archive/lca2003/L - Bilderserie - Perth-UWA"/*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir \
--title="Part 13 - Trip to Fremantle" \
"/tmp/photo-archive/lca2003/M - Bilderserie - Perth-Frementle"/*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir \
--title="Part 14 - Trip to Fremantle" \
"/tmp/photo-archive/lca2003/N - Bilderserie - Fremantle"/*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir \
--title="Part 15 - Return Travel" \
"/tmp/photo-archive/lca2003/O - Bilderserie - Rueckreise"/*.@(jpg|JPG|jpeg|JPEG) \
\
--subdir \
--title="Part 16 - Back at Home" \
"/tmp/photo-archive/lca2003/P - Bilderserie - Ankunft Zuhause"/*.@(jpg|JPG|jpeg|JPEG) \
--
