#!/bin/bash
shopt -s extglob

./slideshow2 \
--directory=lcn2002 \
--maintitle="Thomas Dreibholz's Travel to the LCN2002" --maindescription=lcn2002-maintitle.html \
--stylesheet=stylesheet.css \
--background=background.png \
--shortcuticon=icon-default.png \
--slideshow \
--head=head.html \
--tail=tail.html \
--fullwidth=1280 \
--fullheight=960 \
--enumerate \
\
--block="Part 1" \
"/tmp/photo-archive/lcn2002/Bilderserie 1"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 2" \
"/tmp/photo-archive/lcn2002/Bilderserie 2"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Part 3" \
"/tmp/photo-archive/lcn2002/Bilderserie 3"/*.@(jpg|JPG|jpeg|JPEG) \
$@ \
--
