#!/bin/bash
./slideshow msn2003-index.html $@ \
--maintitle="Thomas Dreibholz's Travel to the MSN2003" --maindescription=msn2003-maintitle.html \
--stylesheet=stylesheet.css \
--enumerate \
\
--subdir=msn2003-block1 \
--title="Part 1 - July 02, 2003" \
"photo-archive/msn2003/2003_07_02/*.JPG \
\
--subdir=msn2003-block2 \
--title="Part 2 - July 03, 2003" \
"photo-archive/msn2003/2003_07_03/*.JPG \
\
--subdir=msn2003-block1 \
--title="Part 3 - July 04, 2003" \
"photo-archive/msn2003/2003_07_04/*.JPG \
\
--subdir=msn2003-block1 \
--title="Part 4 - July 05, 2003" \
"photo-archive/msn2003/2003_07_05/*.JPG \
\
--subdir=msn2003-block1 \
--title="Part 5 - July 06, 2003" \
"photo-archive/msn2003/2003_07_06/*.JPG \
\
--
