#!/bin/bash
./slideshow2 \
--directory=dir-t0 \
--title="Test-Titel" --maindescription=test-maintitle.html \
--stylesheet=stylesheet.css \
--background=background.png \
--shortcuticon=icon-default.png \
--head=head.html \
--tail=tail.html \
--fullwidth=640 \
--fullheight=480 \
--noenumerate \
--block="Some Tests" \
/home/dreibh/tmp/test-jpeg/*.jpg \
--block="Photo Gallery" \
/home/dreibh/tmp/test-jpeg/*.jpeg \
$@ \
