#!/bin/bash
./slideshow2 \
--directory=dir-t0 \
--title="Test-Titel" --maindescription=test-maintitle.html \
--stylesheet=stylesheet.css \
--background=background.png \
--shortcuticon=icon-default.png \
--head=head.html \
--tail=tail.html \
--fullsizewidth=1280 \
--fullsizeheight=960 \
--noenumerate \
--block="Photo Gallery" \
/home/dreibh/tmp/test-jpeg/*.jpeg \
$@ \
