#!/bin/bash
./slideshow test-index.html $@ \
--maintitle="Test-Titel" --maindescription=test-maintitle.html \
--stylesheet=stylesheet.css \
--fullwidth=640 \
--fullheight=480 \
--enumerate \
--subdir \
--title="Some Tests" \
/home/dreibh/tmp/test-jpeg/*.jpg \
--subdir \
--title="Photo Gallery" \
/home/dreibh/tmp/test-jpeg/*.jpeg \
--
