#!/bin/bash
./slideshow t1.html $@ \
--maintitle="Test-Titel" --maindescription=test-maintitle.html \
--stylesheet=stylesheet.css \
--enumerate \
--subdir \
--title="Some Tests" \
/tmp/*.jpg \
--subdir \
--title="Photo Gallery" \
Tux.jpeg \
--
