#!/bin/bash

../slideshow2 \
--infrastructure=../infrastructure \
--directory=demo \
--maintitle="A Slideshow Demo" \
--maindescription=demo-maintitle.html \
--stylesheet=demo-stylesheet.css \
--background=demo-background.png \
--shortcuticon=demo-icon.png \
--slideshow \
--head=demo-head.html \
--tail=demo-tail.html \
--fullsizewidth=1024 \
--fullsizeheight=768 \
--fullsizequality=90 \
--previewquality=80 \
--previewwidth=128 \
--previewheight=96 \
--noenumerate \
--block="1st Block of a Fractal Image Gallery" \
--blockdescription=demo-section1.html \
demo-images/alpha0[1-4]*.png \
--block="2nd Block of a Fractal Image Gallery" \
--blockdescription=demo-section2.html \
demo-images/alpha0[5-8]*.png \
$@ \
