#!/bin/sh
# ---------------------------------------------------------------------------
# -  XHTML 1.1 image presentation and JavaScript-based slideshow generator  -
# ---------------------------------------------------------------------------
#
# Copyright (C) 2003-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com
#

CREATESLIDESHOW=createslideshow
INFRASTRUCTURE=/usr/share/slideshow/infrastructure/
if [ -e ./$CREATESLIDESHOW ] ; then
   CREATESLIDESHOW=./createslideshow
   INFRASTRUCTURE=./infrastructure
elif [ -e ../$CREATESLIDESHOW ] ; then
   CREATESLIDESHOW=../createslideshow
   INFRASTRUCTURE=../infrastructure
fi

$CREATESLIDESHOW \
--directory=demo \
--infrastructure=$INFRASTRUCTURE \
--maintitle="A Slideshow Demo" \
--maindescription=demo-maintitle.html \
--stylesheet=demo-stylesheet.css \
--background=demo-background.png \
--shortcuticon=demo-icon.png \
--slideshow \
--head=demo-head.html \
--tail=demo-tail.html \
--fullsizewidth=1024 \
--fullsizeheight=768 \
--fullsizequality=90 \
--previewquality=80 \
--previewwidth=128 \
--previewheight=96 \
--noenumerate \
--block="1st Block of a Fractal Image Gallery" \
--blockdescription=demo-section1.html \
demo-images/alpha0[1-4]*.png \
--block="2nd Block of a Fractal Image Gallery" \
--blockdescription=demo-section2.html \
demo-images/alpha0[5-8]*.png \
$@ \
