#!/bin/bash
shopt -s extglob

../slideshow2 \
--directory=promotion \
--maintitle="Thomas Dreibholz's Disputation und Absolventenfeier" --maindescription=promotion-maintitle.html \
--stylesheet=stylesheet.css \
--background=background.png \
--shortcuticon=icon-default.png \
--slideshow \
--head=head.html \
--tail=tail.html \
--fullsizewidth=1280 \
--fullsizeheight=960 \
--enumerate \
\
--block="Disputation 07. März 2007- Bilder Rathgeb" \
"/winxp/Dokumente und Einstellungen/root3/Eigene Dateien/Eigene Bilder/Bilder Promotion/Rathgeb"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Disputation 07. März 2007- Bilder Zhou" \
"/winxp/Dokumente und Einstellungen/root3/Eigene Dateien/Eigene Bilder/Bilder Promotion/Zhou"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Disputation 07. März 2007 - Bilder Dreibholz" \
"/winxp/Dokumente und Einstellungen/root3/Eigene Dateien/Eigene Bilder/Bilder Promotion/Dreibholz"/*.@(jpg|JPG|jpeg|JPEG) \
\
--block="Absolventenfeier 11. Mai 2007" \
"/winxp/Dokumente und Einstellungen/root3/Eigene Dateien/Eigene Bilder/Bilder Promotion/Absolventenfeier"/*.@(jpg|JPG|jpeg|JPEG) \
$@ \
--
