.\" $Id: createslideshow.8 254 2009-06-03 12:30:10Z dreibh $
.\"
.\" XHTML/JavaScript Slideshow Generator
.\" Copyright (C) 2003-2011 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@iem.uni-due.de
.\"
.\" ###### Setup ############################################################
.Dd June 13, 2009
.Dt createslideshow 8
.Os createslideshow
.\" ###### Name #############################################################
.Sh NAME
.Nm createslideshow
.Nd XHTML/JavaScript Slideshow Generator
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm createslideshow
.Op xxxxx
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm createslideshow
is a command-line tool to generate standards-compliant XHTML-1.1 presentations from a set of image files. It can be used to easily generate online photo albums, including JavaScript-based slideshows. Particularly, this program is intended to be also used in scripts, which automatically create or update slideshows.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following arguments have to be provided:
.Bl -tag -width indent
.It xxxxx
xxxxx
.It yyyy
yyyy
.El
.\" ###### Arguments ########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It createslideshow ...
.El
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz
.br
http://www.iem.uni-due.de/~dreibh/slideshow
.br
mailto://dreibh@iem.uni-due.de
.br
